#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# https://github.com/lemofire/AutoDailyCP
# Lisence: MIT
# Author: 柠火
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

name: AutoDailyCP

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    - cron: 0 9 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install python3
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install python3
      - name: Download DailyCP
        run: |
          git clone https://gitee.com/Finch1/FuckDailyCP
          mv ./FuckDailyCP/* ./
      - name: Install extensions
        run: |
          pip3 install setuptools
          pip3 install -r requirements.txt
      - name: DIY formdb
        run: |
          # 请根据日志提示的文件名修改此段代码
          cat>formdb/36.json<<EOF
          [{"wid":"474","formWid":"36","fieldType":2,"title":"你的学生类别","description":"","minLength":0,"sort":"1","maxLength":null,"isRequired":1,"imageCount":null,"hasOtherItems":0,"colName":"field001","value":"","minValue":0.0,"maxValue":0.0,"isDecimal":true,"fieldItems":[{"itemWid":"1113","content":"本科生","isOtherItems":0,"contendExtend":null,"isSelected":1},{"itemWid":"1114","content":"硕士生","isOtherItems":0,"contendExtend":null,"isSelected":null},{"itemWid":"1115","content":"博士生","isOtherItems":0,"contendExtend":null,"isSelected":null}]},{"wid":"13775","formWid":"1130","fieldType":2,"title":"目前是否在校","description":"","minLength":0,"sort":"2","maxLength":null,"isRequired":1,"imageCount":null,"hasOtherItems":0,"colName":"field011","value":"","minValue":0.0,"maxValue":0.0,"isDecimal":true,"fieldItems":[{"itemWid":"68548","content":"是","isOtherItems":0,"contendExtend":"","isSelected":1},{"itemWid":"68549","content":"否","isOtherItems":0,"contendExtend":"","isSelected":null}]},{"wid":"475","formWid":"36","fieldType":2,"title":"你今天的体温是多少","description":"","minLength":0,"sort":"3","maxLength":null,"isRequired":1,"imageCount":null,"hasOtherItems":0,"colName":"field002","value":"","minValue":0.0,"maxValue":0.0,"isDecimal":true,"fieldItems":[{"itemWid":"1117","content":"36~37.2℃（正常体温）","isOtherItems":0,"contendExtend":null,"isSelected":1},{"itemWid":"1118","content":"37.3~37.9℃","isOtherItems":0,"contendExtend":null,"isSelected":null},{"itemWid":"1119","content":"38℃及以上","isOtherItems":0,"contendExtend":null,"isSelected":null}]},{"wid":"13768","formWid":"1130","fieldType":2,"title":"你是否有咳嗽、乏力等症状","description":"","minLength":0,"sort":"4","maxLength":null,"isRequired":1,"imageCount":null,"hasOtherItems":0,"colName":"field004","value":"","minValue":0.0,"maxValue":0.0,"isDecimal":true,"fieldItems":[{"itemWid":"68538","content":"否","isOtherItems":0,"contendExtend":"","isSelected":1},{"itemWid":"68537","content":"是","isOtherItems":0,"contendExtend":"","isSelected":null}]},{"wid":"13769","formWid":"1130","fieldType":2,"title":"你今天是否就诊或住院","description":"","minLength":0,"sort":"5","maxLength":null,"isRequired":1,"imageCount":null,"hasOtherItems":0,"colName":"field005","value":"","minValue":0.0,"maxValue":0.0,"isDecimal":true,"fieldItems":[{"itemWid":"68539","content":"否","isOtherItems":0,"contendExtend":"","isSelected":1},{"itemWid":"68540","content":"就诊","isOtherItems":0,"contendExtend":"","isSelected":null},{"itemWid":"68541","content":"住院","isOtherItems":0,"contendExtend":"","isSelected":null}]},{"wid":"492","formWid":"36","fieldType":2,"title":"今天是否有外出行程","description":"","minLength":0,"sort":"7","maxLength":null,"isRequired":1,"imageCount":null,"hasOtherItems":0,"colName":"field019","value":"","minValue":0.0,"maxValue":0.0,"isDecimal":true,"fieldItems":[{"itemWid":"1147","content":"否","isOtherItems":0,"contendExtend":null,"isSelected":1},{"itemWid":"1146","content":"是","isOtherItems":0,"contendExtend":null,"isSelected":null}]},{"wid":"494","formWid":"36","fieldType":2,"title":"本人是否承诺以上所填报的全部内容均属实、准确，不存在任何隐瞒与不实的情况，更无遗漏之处","description":"","minLength":0,"sort":"9","maxLength":null,"isRequired":1,"imageCount":null,"hasOtherItems":0,"colName":"field021","value":"","minValue":0.0,"maxValue":0.0,"isDecimal":true,"fieldItems":[{"itemWid":"1148","content":"是","isOtherItems":0,"contendExtend":null,"isSelected":1},{"itemWid":"1149","content":"否","isOtherItems":0,"contendExtend":null,"isSelected":null}]}]
          EOF
      - name: Run program
        env:
          SCHOOL_NAME: ${{ secrets.SCHOOL_NAME }}
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ADDRESS: ${{ secrets.ADDRESS }}
        run: |
          python3 DailyCP.py ${SCHOOL_NAME} ${ACCOUNT} ${PASSWORD} ${ADDRESS}
      - name : Upload formdb
        uses: actions/upload-artifact@master
        with:
          name: formdb
          path: formdb
